stages:
- name: compile
  steps:
  - runScriptConfig:
      image: ubuntu
      shellScript: |-
        apt-get update
        apt-get install curl -y
        curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh
        ./luvit test
timeout: 60
notification: {}
